apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-hello-world
  labels:
    app: golang-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-hello-world
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: golang-hello-world
    spec:
      terminationGracePeriodSeconds: 30  # Periode grace untuk terminasi pod
      containers:
      - name: golang-hello-world
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:  # Probe untuk menentukan kapan pod siap menerima traffic
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:   # Probe untuk menentukan kapan pod perlu di-restart
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
          preStop:       # Hook yang dipanggil sebelum pod dihentikan
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]  # Memberikan waktu untuk graceful shutdown